ideologies = [

//Totalitarianism
{ "name": "<a href='https://en.wikipedia.org/wiki/Fascism'> Fascism </a>",
  "desc": "Fascism is a form of authoritarian ultranationalism characterized by dictatorial power, forcible suppression of opposition, and strong regimentation of society and of the economy, which came to prominence in early 20th-century Europe.",
  "i18n": { 
    "ko": { "name": "파시즘", 
            "desc": "파시즘은 권위주의적 초국가주의를 수용하는 독재 이데올로기의 한 형태입니다. 조반니 젠틸레는 이 사상을 창시했으며, 유명한 파시스트로는 베니토 무솔리니가 있습니다." },
    "ru": { "name": "Фашизм",
            "desc": "Это форма диктаторской идеологии, которая представляет собой авторитарный ультранационализм. Основателем этой идеологии является Джованни Джентил, а самый известный фашист в истории - Бенито Муссолини." },
    "cn": { "name": "法西斯主义", 
            "desc": "法西斯主义是专制主义的一种形式，它包含了专制的超民族主义。乔万尼•金泰勒（Giovanni Gentile）创立了这种意识形态，著名的法西斯主义者包括墨索里尼。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%B7%E3%82%BA%E3%83%A0'>ファシズム</a>", 
            "desc": "ファシズム（Fascism）は、権威主義的なウルトラナショナリズム（超国家主義）的思想を持つ、独裁を支持する学派の一つです。ジェンティーレ（Giovanni Gentile）を始祖とします。有名なファシストとして、ムッソリーニ（Benito Mussolini）がいます。" }},
"stats": { "a": 20, "b": 85, "c": 90, "d": 10, "e": 50, "f": 50, "g": 80 }},
  
 { "name": "<a href='https://en.wikipedia.org/wiki/Nazism'> National Socialism </a>",
  "desc": "National Socialism, often shortened as Nazism, is a totalitarian ideology that has disdain for liberal democracy and the parliamentary system, and advocates for ideas like antisemitism, anti-communism, scientific racism, German nationalism, and eugenics.",
  "i18n": { 
    "ko": { "name": "나치즘", 
            "desc": "나치즘은 인종과 민족에 근거하여 힘과 기회를 할당하는 파시즘의 한 형태입니다. 그것은 안톤 드렉슬러가 창당하고 아돌프 히틀러가 대중화한 나치당의 이념이었습니다." },
    "ru": { "name": "Нацизм",
            "desc": "Нацизм - это форма фашизма, которая присваивает власть и привелегии на основе расы и этнической принадлежности. Это была идеология Нацистской партии (НСДАП), которая основана Антоном Дрекслером и популяризирована Адольфом Гитлером." },
    "cn": { "name": "纳粹主义", 
            "desc": "纳粹主义是一种基于种族和种族来分配权力和机会的法西斯主义形式。这是纳粹党的意识形态，它是由安东·德雷克斯勒（Anton Drexler）创立并由阿道夫·希特勒（Adolf Hitler）推广的。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E3%83%8A%E3%83%81%E3%82%BA%E3%83%A0'>ナチズム</a>", 
            "desc": "ナチズム（Nazism）は人種や民族性を基に権力を分配することを求める、ファシズムの一派です。 国家社会主義ドイツ労働者党（ナチス）がイデオロギーとして採用した事で有名です。ドレクスラー（Anton Drexler）を始祖とし、ヒトラー（Adolf Hitler）によって広められました。" }},
"stats": { "a": 0, "b": 80, "c": 100, "d": 10, "e": 50, "f": 50, "g": 100 }},


//Monarchism
  
 { "name": "<a href='https://en.wikipedia.org/wiki/Absolute_monarchy'> Absolute Monarchism </a>",
  "desc": "Absolute Monarchism, also called Absolutism, is a form of monarchy in which the monarch holds supreme autocratic authority, principally not being restricted by written laws, legislature, or unwritten customs. These are often hereditary monarchies.",
  "i18n": { 
    "ko": { "name": "절대 군주제", 
            "desc": "절대 군주제는 권위주의적 독재 이념입니다. 군주는 절대적인 권력을 가지고 있고, 지도자는 유전적으로 계승됩니다." },
    "ru": { "name": "Абсолютная Монархия",
            "desc": "это авторитарная идеология. Монархи обладают абсолютной властью, а власть передаётся генетически." },
    "cn": { "name": "绝对君主制", 
            "desc": "绝对君主制是专制独裁的意识形态。君主具有绝对权力，领导者是世袭的。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E7%B5%B6%E5%AF%BE%E5%90%9B%E4%B8%BB%E5%88%B6'>絶対君主制</a>", 
            "desc": "絶対君主主義（Absolute Monarchism）とは、権威主義的な独裁制の一つです。絶対的な権力を持つ君主による政治を理想とします。また、君主の地位は血縁を基に世襲されます。" }},
"stats": { "a": 30, "b": 50, "c": 80, "d": 80, "e": 50, "f": 30, "g": 50 }},
  
 { "name": "<a href='https://en.wikipedia.org/wiki/Constitutional_monarchy'> Constitutional Monarchism </a>",
  "desc": "Constitutional Monarchism is a form of monarchy in which the monarch exercises authority in accordance with a written or unwritten constitution. Within Constitutional Monarchism, the monarch acts as a non-party political head of state under the constitution, whether written or unwritten.",
  "i18n": { 
    "ko": { "name": "입헌 군주제", 
            "desc": "입헌 군주제는 군주제의 변형으로, 군주는 통치할 때 헌법을 따라야 합니다. 그것은 영국, 스페인, 스웨덴 등과 같은 유럽 국가에 존재합니다." },
    "ru": { "name": "Конституционная Монархия",
            "desc": "Это вариант монархизма, когда правящий монарх должен следовать конституции, чтобы править. Он присутствует в европейских странах, таких как Великобритания, Испания, Швеция и т. Д." },
    "cn": { "name": "君主立宪制", 
            "desc": "君主立宪制是君主制的一种变体，统治君主需要遵循宪法才能统治。它存在于英国，西班牙，瑞典等欧洲国家。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E7%AB%8B%E6%86%B2%E5%90%9B%E4%B8%BB%E5%88%B6'>立憲君主主義</a>", 
            "desc": "立憲君主主義（Constitutional Monarchism）とは、君主が憲法に縛られる君主制の一派です。英国やスペイン、スウェーデン王国などヨーロッパの国々は、現在もこの体制下にあります。" }},
"stats": { "a": 30, "b": 30, "c": 60, "d": 40, "e": 50, "f": 50, "g": 50 }},

{ "name": "<a href='https://en.wikipedia.org/wiki/Theocracy'> Theocracy </a>",
  "desc": "Theocracy is a form of government in which a deity of some type is recognized as the supreme ruling authority, giving divine guidance to human intermediaries that manage the day-to-day affairs of the government. In some religions, the ruler, usually a king, was regarded as the chosen favorite of God (or gods) and could not be questioned, sometimes even being regarded as the descendant of or a god in their own right.",
  "i18n": { 
    "ko": { "name": "신정 군주제", 
            "desc": "신정 군주제는 종교를 국가 수반으로 사용하는 군주제이며, 종종 종교 조직을 사용하여 통치합니다." },
    "ru": { "name": "Теократия",
            "desc": "Теократия - это форма правления, при которой власть в государстве находится в руках религиозного учреждения и духовенства. " },
    "cn": { "name": "君权神授制", 
            "desc": "君权神授制是使用宗教作为国家统治工具的君主制，经常使用宗教组织来统治。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E7%A5%9E%E6%A8%A9%E6%94%BF%E6%B2%BB'>神権主義</a>", 
            "desc": "神権主義（Theocracy）とは、宗教や宗教的指導者を君主とする君主制を支持する思想です。多くの場合、宗教団体を用いた政治が行われます。" }},
"stats": { "a": 20, "b": 50, "c": 85, "d": 50, "e": 10, "f": 40, "g": 50 }}, 



//Liberals, Libertarians

 { "name": "<a href='https://en.wikipedia.org/wiki/Right-Libertarianism'> Libertarianism </a>",
  "desc": "Libertarianism, or more specifically Right-Libertarianism, is a political philosophy and movement that upholds liberty as a core principle. Libertarians seek to maximize autonomy and political freedom, emphasizing free association, freedom of choice, individualism and voluntary association.",
  "i18n": { 
    "ko": { "name": "자유주의", 
            "desc": "자유주의자들은 일반적으로 문화적으로는 진보적지만 경제적으로는 보수적입니다. 그들은 비자발적인 세금 폐지는 물론 더 작은 주/정부를 원합니다." },
    "ru": { "name": "Либертарианство",
            "desc": "Либертарианцы, как правило, культурно левые, но финансово консервативные, и хотят меньшего государства/правительства, а также отмены принудительных налогов." },
    "cn": { "name": "自由主义", 
            "desc": "自由主义者通常在文化上是激进的，但在财政上是保守的，他们想要一个较小的政府，以及废除强制纳税。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E3%83%AA%E3%83%90%E3%82%BF%E3%83%AA%E3%82%A2%E3%83%8B%E3%82%BA%E3%83%A0'>リバタリアニズム</a>", 
            "desc": "リバタリアニズム（Libertarianism）は自由至上主義とも訳されます。リバタリアンの多くは文化については左翼的である一方、経済に関しては右派です。小さな国家／政府を支持し、自由意志で拒否できない税制の廃止を主張します。" }},
"stats": { "a": 60, "b": 10, "c": 20, "d": 70, "e": 50, "f": 80, "g": 50 }},
  
 { "name": "<a href='https://en.wikipedia.org/wiki/Individualist_Anarchism'> Individualist Anarchism </a>",
  "desc": "Individualist anarchism is the branch of anarchism that emphasizes the individual and their will over external determinants such as groups, society, traditions and ideological systems.",
  "i18n": { 
    "ko": { "name": "개인주의 아나키즘", 
            "desc": "개인주의 아나키즘은 개인주의를 강하게 옹호하는 무정부주의의 한 형태이며, 아나키즘 정부를 지지합니다." },
    "ru": { "name": "Индивидуалистический анархизм",
            "desc": "Индивидуалистический анархизм-это форма анархизма, которая решительно выступает за индивидуализм, а также поддерживает анархическое идеи." },
    "cn": { "name": "个人无政府主义", 
            "desc": "个人无政府主义是强烈倡导个人主义并支持无政府主义的意识形态。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E5%80%8B%E4%BA%BA%E4%B8%BB%E7%BE%A9%E7%9A%84%E7%84%A1%E6%94%BF%E5%BA%9C%E4%B8%BB%E7%BE%A9'>個人主義的無政府主義</a>", 
            "desc": "個人主義的無政府主義（Individualist Anarchism）は、個人主義を強く主張する無政府主義の一派です。" }},
"stats": { "a": 50, "b": 20, "c": 5, "d": 65, "e": 50, "f": 60, "g": 50 }},
    
 { "name": "<a href='https://en.wikipedia.org/wiki/Agorism'> Agorism </a>",
  "desc": "Agorism is a free-market anarchist political philosophy that supports bringing about a society in which all relations between people are voluntary exchanges, and aims to achieve this through counter-economics.",
  "i18n": { 
    "ko": { "name": "아고리즘", 
            "desc": "아고리즘은 아나키즘의 분파로써 모든 인간 관계가 평화로운 혁명과 반경제적인 것에 의해 이루어져야한다고 생각합니다." },
    "ru": { "name": "Агоризм",
            "desc": "Агоризм - это анархистская политическая философия свободного рынка, которая поддерживает создание общества, в котором все отношения между людьми являются добровольными обменами, и стремится достичь этого с помощью контрэкономики. " },
    "cn": { "name": "黑市主义（阿哥拉主义)", 
            "desc": "黑市主义者认为所有人类关系都应通过和平革命和反经济学来完成。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Agorism'>アゴリズム</a>", 
            "desc": "アゴリズム（Agorism）とは、ブラックマーケットやグレーマーケットを活用した非暴力革命を通し、あらゆる人間が能動的な契約に基づく交流を行う社会を実現することを志向する思想です。" }},
"stats": { "a": 50, "b": 40, "c": 0, "d": 80, "e": 50, "f": 60, "g": 50 }},

{ "name": "<a href='https://en.wikipedia.org/wiki/Anarcho-Capitalism'> Anarcho-Capitalism </a>",
  "desc": "Anarcho-Capitalism is a political philosophy and economic theory that advocates the elimination of centralized states in favor of a system of private property enforced by private agencies, free markets and the right-libertarian interpretation of self-ownership, which extends the concept to include control of private property as part of the self.",
  "i18n": { 
    "ko": { "name": "아나코-자본주의", 
            "desc": "아나코-자본주의는 개인의 권리와 자유에 매우 높은 우선순위를 두는 무정부주의 이념입니다. 그것은 무정부상태와 자본주의의 극단적인 형태이고, 세금을 도둑질의 한 형태로 간주합니다." },
    "ru": { "name": "Анархо-Капитализм",
            "desc": "Это анархистская идеология, которая ставит очень высокий приоритет правам и свободе личности. Это крайняя форма анархии и капитализма. Он рассматривает налогообложение как форму воровства." },
    "cn": { "name": "无政府资本主义", 
            "desc": "无政府资本主义是一种无政府主义意识形态，在个人权利和自由方面具有很高的优先地位。它是无政府状态和资本主义的极端形式。它认为税收是盗窃的一种形式。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E7%84%A1%E6%94%BF%E5%BA%9C%E8%B3%87%E6%9C%AC%E4%B8%BB%E7%BE%A9'>無政府資本主義</a>", 
            "desc": "無政府資本主義（アナルコキャピタリズム；Anarcho-Capitalism）とは、個人の自由や権利をつよく優先する思想です。徴税は窃盗であるとつよく主張し、政府が廃止された自由市場に基づく資本主義を提唱します。" }},
"stats": { "a": 50, "b": 0, "c": 0, "d": 80, "e": 50, "f": 80, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Night-watchman_state'> Minarchism </a>",
  "desc": "Minarchism maintains that the state's only legitimate function is the protection of individuals from aggression, theft, breach of contract, and fraud, and the only legitimate governmental institutions are the military, police, and courts. Similarly to other Libertarian ideologies, it emphasizes on freedom of speech, property, and voluntary association.",
  "i18n": { 
    "ko": { "name": "소정부주의", 
            "desc": "소정부주의는 매우 작은 정부를 원하는 이념입니다. 그들은 정부의 목적이 단지 법을 집행하기 위한 것이라고 생각합니다. 이런 형태의 정부는 '야경꾼 국가'라고 불립니다." },
    "ru": { "name": "Минархизм",
            "desc": "это идеология, которая хочет иметь очень никзкое вмешательство правительства. Они думают, что цель правительства только в том, чтобы исполнять законы." },
    "cn": { "name": "最小政府主義", 
            "desc": "最小政府主義是一个需要很小的政府的意识形态。他们认为政府的目的只是为了执行法律。这种政府被称为守夜人政府。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E6%9C%80%E5%B0%8F%E5%9B%BD%E5%AE%B6%E4%B8%BB%E7%BE%A9'>最小国家主義</a>", 
            "desc": "最小国家主義（ミナキズム；Minarchism）とは、国民を暴力やその他個人を害する行為からのみ守る政府（最小国家）を提唱する思想です。最小国家は夜警国家とも呼ばれます。" }},
"stats": { "a": 50, "b": 5, "c": 10, "d": 80, "e": 50, "f": 30, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Paleolibertarianism'> Paleolibertarianism </a>",
  "desc": "Paleolibertarianism is a variant of Libertarianism which stresses inherent incompatibility between progressivism and the concept of liberty, as well as a focus on the importance of inherited culture as a means of maintaining order. ",
  "i18n": { 
    "ko": { "name": "고자유주의", 
            "desc": "고자유주의는 기본적으로 자유주의이지만 문화적으로는 보수적입니다. 그들은 작은 정부를 원합니다." },
    "ru": { "name": "Палеолибертарианство",
            "desc": "Палеолибертарианцы в основном либетарианцы, но консервативны и в культурном отношении. Они хотят небольшое государство." },
    "cn": { "name": "古希腊主义", 
            "desc": "古希腊主义者基本上是自由主义者，但在文化上也很保守。他们想要一个小国家。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Paleolibertarianism'>パレオ・リバタリアニズム</a>", 
            "desc": "パレオ・リバタリアニズム（Paleolibertarianism）とは、文化に対しては保守主義的姿勢を取るリバタリアン（自由至上主義）の一派です。小さな国家を主張します。" }},
"stats": { "a": 30, "b": 10, "c": 30, "d": 60, "e": 50, "f": 60, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Geolibertarianism'>Geolibertarianism </a>",
  "desc": "Geolibertarianism is a political and economic ideology that integrates libertarianism with Georgism, and holds that although people should own the value they produce themselves, all land should belong equally to all members of society. It does not consider land as legitimate private property.",
  "i18n": { 
    "ko": { "name": "토지-자유주의", 
            "desc": "토지-자유주의는 자유주의적인 가치를 가진 지공주의의 분파입니다 지공주의는 토지가 사유재산으로 간주되지 않고 세금과 공소유지를 받는 경제체제입니다." },
    "ru": { "name": "Геолибертарианство",
            "desc": "это джорджизм с либертарианскими ценностями. Джорджизм -это экономическая система, в которой земля не считается частной собственностью, а облагается налогом и находится в государственной собственности." },
    "cn": { "name": "地缘自由主义", 
            "desc": "地缘自由主义是具有自由主义者价值观的乔治主义者。乔治主义是一种土地不被视为私有财产，而是共有且使用者被征税的经济体系。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Geolibertarianism'>ジオ・リバタリアニズム</a>", 
            "desc": "ジオ・リバタリアニズム（Geo-Libertarianism）は、土公主義（ジョージ主義；Georgism）的価値観を持つリバタリアニズム（自由至上主義）思想です。土公主義者は土地を公的所有されているものと見なし、土地所有者につよい税をかけ、土地税以外のあらゆる税の廃止を提唱します。" }},
"stats": { "a": 50, "b": 60, "c": 20, "d": 65, "e": 50, "f": 60, "g": 50 }},

{ "name": "<a href='https://en.wikipedia.org/wiki/Neoliberalism'> Neoliberalism </a>",
  "desc": "Neoliberalism is generally associated with policies of economic liberalization, including privatization, deregulation, globalization, free trade, and tricke-down economics, and served as the opposition of Keynesian Economics.",
  "i18n": { 
    "ko": { "name": "신자유주의", 
            "desc": "신자유주의는 자유시장 중심의 개혁 이념으로 대개 문화적으로 좌편향적입니다. 국가의 영향력을 줄이는 것도 이념의 큰 부분입니다." },
    "ru": { "name": "Неолиберализм",
            "desc": "это ориентированная на свободный рынок реформаторская идеология, которая обычно культурно левая. Снижение влияния государства также является большой частью идеологии." },
    "cn": { "name": "新自由主义", 
            "desc": "新自由主义是一种以自由市场为导向的改革思想，通常在文化上是激进的。减少政府影响也是该思想的重要组成部分。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E6%96%B0%E8%87%AA%E7%94%B1%E4%B8%BB%E7%BE%A9'>新自由主義</a>", 
            "desc": "新自由主義（ネオリベラリズム；Neo-Liberalism）とは、、自由市場志向の社会改良を求める思想です。文化に対しては左翼的思想を持ちます。また、国家の権力を縮小することも主張します。" }},
"stats": { "a": 60, "b": 25, "c": 50, "d": 50, "e": 50, "f": 70, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Classical_Liberalism'> Classical Liberalism </a>",
  "desc": "Classical liberalism is a political ideology and a branch of liberalism that advocates civil liberties under the rule of law with an emphasis on economic freedom. Highly influenced by the Enlightenment, it believes in a limited government that protects individual rights, and limited public services and welfare.",
  "i18n": { 
    "ko": { "name": "고전적 자유주의", 
            "desc": "고전적 자유주의는 개인의 자유와 제한적인 정부를 자유사회의 기초로 봅니다. 그것은 자유주의적 이상을 가진 최초의 이념들 중 하나였습니다." },
    "ru": { "name": "Классический либерализм",
            "desc": "Класси́ческий либерали́зм — политическая идеология, ветвь либерализма, которая утверждает гражданские права и политическую свободу." },
    "cn": { "name": "古典自由主义", 
            "desc": "古典自由主义将个人自由和有限的政府视为自由社会的基础。 它是最初具有自由主义理想的意识形态之一。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E5%8F%A4%E5%85%B8%E7%9A%84%E8%87%AA%E7%94%B1%E4%B8%BB%E7%BE%A9'>古典的自由主義</a>", 
            "desc": "古典的自由主義（Classical Liberalism）とは、個人の自由と小さな政府を前提とした自由社会を求める立場です。新自由主義などの、より新しい自由主義のもととなった思想で、これらと区別するために「古典的」と呼ばれます。" }},
"stats": { "a": 40, "b": 20, "c": 30, "d": 65, "e": 50, "f": 50, "g": 50 }}, 


//Traditionalism

 { "name": "<a href='https://en.wikipedia.org/wiki/Conservatism'> Conservatism </a>",
  "desc": "Conservatism is a cultural, social, and political philosophy which seeks to promote and to preserve traditional social institutions. n Western culture, conservatives seek to preserve a range of institutions such as organized religion, parliamentary government, and property rights.",
  "i18n": { 
    "ko": { "name": "보수주의", 
            "desc": "보수주의는 주로 현상유지에 관한 이념입니다. 보수주의자들은 대개 외교적 개입주의, 더 많은 군사비 지출, 더 낮은 세금을 지지합니다." },
    "ru": { "name": "Консерватизм",
            "desc": "это идеология, которая в основном направлена на сохранение статус-кво. Консерваторы обычно поддерживают дипломатический интервенционизм, увеличение военных расходов и снижение налогов." },
    "cn": { "name": "保守主义", 
            "desc": "保守主义是一种倾向于主要是维护现状的意识形态。保守主义者通常支持外交干预主义，增加军费开支和降低税收。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E4%BF%9D%E5%AE%88'>保守主義</a>", 
            "desc": "保守主義(Conservatism)とは、現状維持を強く主張する思想の一つです。保守主義者の多くは他国への積極的な干渉を支持し（干渉主義）、軍事予算 の増加や税の引き下げを主張します。" }},
"stats": { "a": 30, "b": 20, "c": 40, "d": 30, "e": 50, "f": 50, "g": 50 }},

 { "name": "<a href='https://en.wikipedia.org/wiki/Neoconservatism'> Neoconservatism </a>",
  "desc": "Neoconservatives typically advocate the promotion of democracy and interventionism in international affairs, including peace through strength, and are known for espousing disdain for communism and political radicalism.",
  "i18n": { 
    "ko": { "name": "신보수주의", 
            "desc": "신보수주의는 자유주의 정당의 태평양주의 정책을 싫어하는 보수주의의 한 형태입니다. 신보수주의자들은 서구 국가들의 목표가 자신들의 모델을 세계에 알리는 것이라고 생각합니다. 그들은 더 국제적으로 초점을 맞추고 있습니다." },
    "ru": { "name": "Неоконсерватизм",
            "desc": "это идеология,в основе которой лежат идеи консерватизма, приспособленных к новым условиям общественного развития. Неоконсерваторы считают, что цель западных стран-донести до мира свою модель. Они более ориентированы на международный уровень." },
    "cn": { "name": "新保守主义", 
            "desc": "新保守主义是保守主义的一种形式，它不喜欢自由党的太平洋主义政策。新保守主义者认为西方国家的目标是将自己的榜样推向世界。它们更加国际化。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E6%96%B0%E4%BF%9D%E5%AE%88%E4%B8%BB%E7%BE%A9'>新保守主義</a>", 
            "desc": "新保守主義（Neo-Conservatism）は、リベラル政党のハト派政策に反対する保守主義の一派です。新保守主義者は、西洋諸国の思想や政治体制を積極的に世界中に広めることを主張します。海外を強く意識しているのが特徴です。" }},
"stats": { "a": 20, "b": 20, "c": 65, "d": 15, "e": 50, "f": 60, "g": 50 }},

{ "name": "<a href='https://en.wikipedia.org/wiki/Centre-Right_Politics'> Centre-Right Politics </a>",
  "desc": "Center-Right Politics lean to the right of the political spectrum, but are closer to the centre than others. It is influenced by economics liberalism and neoliberalism, but also supports certain left-leaning ideas such as a welfare state and egalitarianism.",
  "i18n": { 
    "ko": { "name": "중도 우파", 
            "desc": "중도 우파는 우파 성향의 중도주의입니다. 온건 보수적인 것 말고는, 중도 우파는 대부분의 다른 견해에서는 중립적입니다." },
    "ru": { "name": "Правый центризм",
            "desc": "Это люди умеренных правых взглядов. Помимо того, что они умеренно консервативны, они нейтральны в большинстве других взглядов." },
    "cn": { "name": "中间派右翼主义", 
            "desc": "中间派右翼主义是右倾的中间派意识形态。除了适度的保守主义外，它们在大多数其他观点中都是中立的。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E4%B8%AD%E9%81%93%E5%8F%B3%E6%B4%BE'>中道右派</a>", 
            "desc": "中道右派（Centre-Rightism）の人は、文化についてはやや保守的な傾向をもつものの、その他の価値観については中立的な立場をとります。" }},
"stats": { "a": 60, "b": 50, "c": 50, "d": 50, "e": 50, "f": 50, "g": 50 }}, 


{ "name": "<a href='https://en.wikipedia.org/wiki/Reactionary'> Reactionary Conservatism </a>",
  "desc": "Reactionary Conservatism, or Reactionaryism, favor a return to a previous political state of society that they believe possessed positive characteristics that are absent in contemporary society. In modern terms, Reactionary Conservatism refers to a highly traditional position that is opposed to social or political change, that tends to stand in opposition against Enlightenment ideas.",
  "i18n": { 
    "ko": { "name": "반동 보수주의", 
            "desc": "반동주의는 구체제로 돌아가려는 정치 이념으로서 진보주의에 대한 반대 개념이다." },
    "ru": { "name": "Политическая реакция",
            "desc": "политическая реакция — общественное движение в направлении, резко противоположном предшествовавшему или современному общественному строю." },
    "cn": { "name": "反动保守主义", 
            "desc": "反动保守主义是一种意识形态，其思想是保存文化并退后一步，以恢复过去的政府体制，无论是帝国主义还是古典保守主义。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E5%BE%A9%E5%8F%A4%E4%B8%BB%E7%BE%A9'>復古主義</a>", 
            "desc": "復古主義（Reactionary Conservatism）とは、文化の保守や過去の政治体制の復活を支持します。場合によっては帝国主義（imperialism）を主張することもあります。" }},
"stats": { "a": 0, "b": 20, "c": 80, "d": 20, "e": 50, "f": 50, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Paleoconservatism'> Paleoconservatism </a>",
  "desc": "Paleoconservatism is a political philosophy and variety of conservatism in the United States stressing nationalism, Christian ethics, regionalism, and traditionalist conservatism. Their views overlap with the Old Right and Right-Wing Populism.",
  "i18n": { 
    "ko": { "name": "고보수주의", 
            "desc": "고보수주의는 종교, 민족주의, 전통주의를 강조하는 보수주의의 변형입니다." },
    "ru": { "name": "Палеоконсерватизм",
            "desc": "Палеоконсерватизм-это разновидность консерватизма, подчеркивающая религиозность, национализм и традиционализм." },
    "cn": { "name": "古典保守主义", 
            "desc": "古典保守主义是保守主义的一种变体，它强调宗教，民族主义和传统主义。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Paleoconservatism'>パレオ保守主義</a>", 
            "desc": "パレオ保守主義(Paleoconservatism)とは、保守主義のうち、宗教、国民、伝統を強く重視することを非常に強く訴える一派です。" }},
"stats": { "a": 25, "b": 40, "c": 60, "d": 35, "e": 50, "f": 40, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Right-wing_populism'> Right-Wing Populism </a>",
  "desc": "Right-Wing Populism is a political ideology which combines right-wing politics and populist rhetoric and themes. The rhetoric often consists of anti-elitist and anti-intellectual sentiments, opposition to the Establishment, and speaking to the 'common people'.",
  "i18n": { 
    "ko": { "name": "우익 포퓰리즘", 
            "desc": "우익 포퓰리즘은 우파적 가치와 포퓰리즘이 결합된 이념입니다. 우익 포퓰리스트들은 대개 민족주의적이고 보호주의적이며 이민에 대한 더 강력한 규제를 지지합니다." },
    "ru": { "name": "Патерналистский консерватизм",
            "desc": "Патернали́стский консервати́зм — ответвление консерватизма, отражающее идею того, что сообщества функционируют и развиваются взаимозависимо, и что люди внутри них имеют обязательства друг перед другом." },
    "cn": { "name": "右翼民粹主义", 
            "desc": "右翼民粹主义是将右翼价值观与民粹主义相结合的意识形态。右翼民粹主义者通常是民族主义，保护主义，并支持更严格的移民限制。" },
    "ja": { "name": "<a href='https://ja.wikipedia.org/wiki/%E5%8F%B3%E6%B4%BE%E3%83%9D%E3%83%94%E3%83%A5%E3%83%AA%E3%82%BA%E3%83%A0'>右翼ポピュリズム</a>", 
            "desc": "右翼ポピュリズム（Right-Wing Populism）とは、右翼的価値観をもったポピュリズム（大衆主義）です。ナショナリズム的な傾向を持ち、保護貿易と移民の規制を主張します、" }},
"stats": { "a": 30, "b": 55, "c": 65, "d": 55, "e": 50, "f": 50, "g": 50 }}, 

 { "name": "<a href='https://en.wikipedia.org/wiki/Paternalistic_conservatism'> Paternalistic Conservatism </a>",
  "desc": "Paternalistic conservatism is a strand of conservatism with an emphasis on the paternalistic obligation of those who are privileged and wealthy to the poorer parts of society.",
  "i18n": { 
    "ko": { "name": "우익 사회주의", 
            "desc": "우익 사회주의 는 시장 경제, 상업주의, 자유 방임, 내셔널리즘 등 우파적인 가치를 바탕으로 한 공동체주의를 의미한다." },
    "ru": { "name": "Патерналистский консерватизм",
            "desc": "это идеология, которая в основном направлена на сохранение статус-кво. Консерваторы обычно поддерживают дипломатический интервенционизм, увеличение военных расходов и снижение налогов." },
    "cn": { "name": "家长式保守主义", 
            "desc": "家长式保守主义是保守主义的一个分支，主张富人有责任支持穷人。 " },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Paternalistic_conservatism'> 父性的保守主義</a>", 
            "desc": "父性的保守主義(Paternalistic Conservatism)は保守主義の一分野であり、貧しい人々を支援するために裕福な人々の義務を強調します。 " }},
"stats": { "a": 40, "b": 65, "c": 60, "d": 40, "e": 50, "f": 50, "g": 50 }},
  
 { "name": "<a href='https://en.wikipedia.org/wiki/Fiscal_conservatism'> Fiscal Conservatism </a>",
  "desc": "Fiscal conservatism is a political and economic philosophy regarding fiscal policy and fiscal responsibility advocating privatization, low taxes, reduced government spending and minimal government debt.",
  "i18n": { 
    "ko": { "name": "재정보수주의", 
            "desc": "재정보수주의 는 재정 정책과 관련하여 재정 책임의 옹호의 정치 철학이다. 재정보수주의자들은 종종 피고려 적자 지출과 전체 정부 지출 및 국가 부채의 감소뿐만 아니라 균형 예산을 중요시한다." },
    "ru": { "name": "Фискальный консерватизм",
            "desc": "Фискальный консерватизм, представляет собой политическую и экономическую философию, касающуюся фискальной политики и фискальной ответственности, выступающую за низкие налоги, сокращение государственных расходов и минимальный государственный долг." },
    "cn": { "name": "财政保守主义", 
            "desc": "财政保守主义是用来形容主张避免赤字开支的保守主义财政政策。财政保守主义者往往支持减少整体政府开支、赤字和国债，以达到最重要的平衡预算。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Fiscal_conservatism'>財政保守主義</a>", 
            "desc": "財政保守主義(Fiscal Conservatism)は、低税、政府支出の削減、最小限の政府債務を提唱する、財政政策と財政責任に関する政治的および経済的哲学です。" }},
"stats": { "a": 40, "b": 10, "c": 40, "d": 20, "e": 50, "f": 50, "g": 50 }},
  
//Others

{ "name": "<a href='https://en.wikipedia.org/wiki/Rainbow_capitalism'> Pink Capitalism </a>",
  "desc": "Pink Capitalism is the incorporation of the LGBT movement and sexual diversity into consumerism and capitalism, in order to create a market that is oriented and tolerated towards LGBT communities.",
  "i18n": { 
    "ko": { "name": "핑크 자본주의", 
            "desc": "핑크 자본주의는 LGBT 운동, 성적 다양성, 핑크워싱을 자본주의에 통합한 것입니다." },
    "ru": { "name": "Розовый капитализм",
            "desc": "это идеология, которая стремится включить прогрессивизм в капитализм. Он поддерживает рынок невмешательства и, как правило, также поддерживает минимальное или несуществующее правительство." },
    "cn": { "name": "粉色资本主义", 
            "desc": "粉色资本主义是一种旨在将进步主义纳入资本主义的意识形态。它支持自由放任的市场。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Rainbow_capitalism'>ピンク・キャピタリズム</a>", 
            "desc": "ピンク・キャピタリズム(Pink Capitalism)とは、レインボーキャピタリズムとも言われ、LGBTQの権利拡大を主張しつつ自由放任市場を支持する資本主義の一派です。" }},
"stats": { "a": 80, "b": 10, "c": 30, "d": 30, "e": 50, "f": 70, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Civic_Nationalism'> Civic Nationalism </a>",
  "desc": "Civic Nationalism is a form of nationalism identified by political philosophers who believe in an inclusive form of nationalism that adheres to traditional liberal values of freedom, tolerance, equality, and individual rights.",
  "i18n": { 
    "ko": { "name": "시민 민족주의", 
            "desc": "시민 민족주의는 민족주의와 자유주의를 결합합니다. 이는 자유주의, 개인주의, 평등과 같은 자유주의적 가치와 서양 기준의 전통적 가치를 지지하는 민족주의의 한 형태입니다." },
    "ru": { "name": "Гражданский национализм",
            "desc": "Гражданский национализм сочетает национализм с либерализмом. Это форма национализма, которая поддерживает либеральные и Традиционные (по западным стандартам) ценности, такие как Свобода, Индивидуальность и Равенство." },
    "cn": { "name": "公民民族主义", 
            "desc": "公民民族主义将民族主义与自由主义相结合。这是一种支持自由主义和传统（按照西方标准）价值观（例如自由，个性和平等）的民族主义。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Civic_Nationalism'>市民民族主義</a>", 
            "desc": "市民民族主義（Civic Nationalism）とは、リベラリズム的思想を持ったナショナリズムです。市民の自由や個人主義、そして平等を主張します。" }},
"stats": { "a": 60, "b": 30, "c": 50, "d": 50, "e": 50, "f": 50, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Progressive_Conservatism'> Progressive Conservatism </a>",
  "desc": "Progressive conservatism is a political ideology which combines conservative and progressive policies. It believes that social reform and progression in areas such as science, economics, education, technology and medicine were necessary to improve human living conditions, but also supports the preservation of tradition.",
  "i18n": { 
    "ko": { "name": "진보적 보수주의", 
            "desc": "진보적 보수주의는 보수적 가치와 진보적 가치의 결합입니다. 진보적 보수주의자들은 사회가 개혁되어야 하지만 보수주의적인 사고를 통해 성취되어야 한다고 믿습니다." },
    "ru": { "name": "Прогрессивный консерватизм",
            "desc": "Прогрессивный консерватизм-это сочетание консервативных и прогрессивных ценностей. Он считает, что общество должно быть реформировано, но должно быть достигнуто с помощью консервативного мышления." },
    "cn": { "name": "进步保守主义", 
            "desc": "进步保守主义是一个来自于保守主義的思想意识，它依附于保守主義政策的基础上合并了進步主義的制度政策。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Progressive_Conservatism'>革新的保守主義</a>", 
            "desc": "革新的保守主義（Progressive Conservatism）とは、社会改良主義的思想を持った保守です。社会に改良が必要であることを認めつつ、保守的態度を通した社会改革を求めます。" }},
"stats": { "a": 70, "b": 40, "c": 40, "d": 50, "e": 50, "f": 70, "g": 50 }}, 

{ "name": "<a href='https://en.wikipedia.org/wiki/Technocracy'> Technocracy </a>",
  "desc": "Technocracy is a system of government in which a decision-maker or makers are elected by the population or appointed on the basis of their expertise in a given area of responsibility, particularly with regard to scientific or technical knowledge.",
  "i18n": { 
    "ko": { "name": "기술관료제", 
            "desc": "기술관료제는 기술 전문가인 사람이 국가를 통치해야 한다는 사상을 지지하는 이념입니다." },
    "ru": { "name": "Технократия",
            "desc": "это идеология, которая продвигает идею о том, что люди, которые являются экспертами в области технологий, должны править нацией." },
    "cn": { "name": "科技专制", 
            "desc": "在科技专制中，决策者是根据其在给定责任领域（尤其是在科学或技术知识方面）的专业知识来选拔的。" },
    "ja": { "name": "<a href='https://en.wikipedia.org/wiki/Technocracy'>技術官僚主義</a>", 
            "desc": "技術官僚主義（テクノクラシー；Technocracy）あるいは技術家主義とは、高度な専門的知識を持つ技術家を官僚（テクノクラート）とし、テクノクラートを中心とした政治体制を求める思想です。" }},
"stats": { "a": 60, "b": 60, "c": 60, "d": 60, "e": 50, "f": 80, "g": 50 }}

];
