questions = [

//Reform vs Conserve
{ "question": "Homosexuality is against my personal values.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "A crackdown on pornography is beneficial to society.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The negatives of rapid reform outweighs its positives.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I disagree with most of the values that Progressivism advocates.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Abortion is murder and should be criminalized.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Gender is a social construct.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support (Third/Fourth) Wave Feminism.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The LGBT movement deserves more respect.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support criminal justice reform in my country.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
//Intervention vs Laissez-Faire
{ "question": "The freer the markets, the freer the people.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Economic regulation causes economic stagnation and the overall reduction of productivity.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Some, if not all forms of taxation is theft.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The gain of companies within the market directly correlate to the gain of the individual.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Government is a bigger cause of economic inequality than Capitalism is.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Economic regulation is necessary for a fair and equal society.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I prefer a planned economy over a market economy.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "It is necessary for the government to intervene in the economy to protect its consumers.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "We need to have more welfare compared to what we have currently.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The minimum wage should be increased.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
//Dictatorship vs Constitution
{ "question": "The state should be abolished.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I would rather have a constitutional monarchy than an absolute monarchy.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support a constitution that limits the state's power.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Rights are inalienable and natural, as government is not the source of our rights.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The state can be best defined as a monopoly on violence.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },

{ "question": "A strong government is required for a safe society.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I prioritize security over liberty.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I prefer a unitary state over a federal state.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Theoretically, a morally good dictator would bring more good than bad.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Strong governments are more efficient than democratic governments.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
//Particular vs Universal
{ "question": "My nation's ideals are better than most other nation's ideals.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The enemy of my enemy is my friend.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Foreign intervention is sometimes necessary.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Foreign officials have no right to dictate policy in another country.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "My country's borders should be expanded.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "We should avoid conflict when possible.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Political unions like the EU generally do more harm than good.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support isolationism.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support a non-interventionist foreign policy.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "My country spends too much money on the military.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
//Theocracy vs Secular
{ "question": "Public schools should not advocate for any religious belief.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "Religion should play a much smaller role in government.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "Churches should be taxed the same way as how most other organizations are taxed.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "The church and state needs to be seperated.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "All theocracies are tyrannies.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "There should be one or more official religion(s) in my country.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
{ "question": "Public schools should teach students to be followers of my religion.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
{ "question": "My nation is inherently a religious nation.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
{ "question": "Secularism is unhealthy for society.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
{ "question": "If I can vote, I would consider the candidates' religious beliefs when voting.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
//Acceleration vs Deceleration
{ "question": "Rapid technological advancement causes more harm than good.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },

{ "question": "Life before the industrial revolution was much better.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },
	
{ "question": "Modern urban life is unfulfilling because of technological development.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },
	
{ "question": "If given the choice, I would reject an extension of my lifespan by centuries.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },
	
{ "question": "Transhumanism is an absurd idea.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },
	
{ "question": "It is foolish to expect renewable energy sources to be able to fully replace fossil fuels.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },

{ "question": "We should accelerate our technological progress.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },
	
{ "question": "Promoting nuclear energy is more effective than implementing environmental regulations.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },
	
{ "question": "Space colonization as an issue should be considered more seriously.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },
	
{ "question": "Currently, people are too paranoid about AI.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },
	
//Assimilation vs Multicultural
{ "question": "Governments should be as concerned about foreign citizens as they are about those within their borders.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },
	
{ "question": "Most, if not all societies should be a blend of different cultures.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },
	
{ "question": "Borders should be as open as possible.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },
	
{ "question": "There shouldn't be an official language in my country.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },
	
{ "question": "Nativism is discriminatory in nature.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },

{ "question": "In general, immigrants are bad for the country.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
{ "question": "Immigrants should be expected to learn the majority language of the country.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
{ "question": "Immigrants can never really adapt to our way of life.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
{ "question": "There should be a shared and unified cultural identity in my country.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
{ "question": "If we accept migrants at all, it is important that they assimilate into our culture.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
];
