questions = [

//Reform vs Conserve
{ "question": "Homosexuality is against my personal values.",
"i18n":{"ko": "동성애는 나의 개인적인 도덕적 가치에 어긋난다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "A crackdown on pornography is beneficial to society.",
"i18n":{"ko": "포르노에 대한 단속은 사회에 도움이 된다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The usage of marijuana is immoral and should be criminalized.",
"i18n":{"ko": "대마초는 범죄화되어야 합니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I disagree with most of the values that Progressivism advocates.",
"i18n":{"ko": "나는 진보주의가 옹호하는 대부분의 가치관에 동의하지 않는다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Abortion is murder and should be criminalized in most or all cases.",
"i18n":{"ko": "낙태의 합법화는 유익하다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": -5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Gender is a social construct.",
"i18n":{"ko": "성별간의 역할 차이는 사회적으로 구성된 것이다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support (Third/Fourth) Wave Feminism.",
"i18n":{"ko": "나는 성소수자(3세대)와 정치적 올바름(4세대)을 위한 페미니즘을 지지한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The LGBT movement deserves more respect.",
"i18n":{"ko": "성소수자 운동은 더 존중 받을 만하다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support criminal justice reform in my country.",
"i18n":{"ko": "나는 우리나라의 형사 사법 개혁을 지지합니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 5, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
//Intervention vs Laissez-Faire
{ "question": "The freer the markets, the freer the people.",
"i18n":{"ko": "시장이 자유로울수록, 사람들은 자유로워진다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Economic regulation causes economic stagnation and the overall reduction of productivity.",
"i18n":{"ko": "경제 규제는 경제 침체와 전반적인 생산성 감소를 야기한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Insurance should be used voluntarily by individuals rather than welfare.",
"i18n":{"ko": "보험은 복지보다는 개인이 자발적으로 사용해야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The gain of companies within the market directly correlate to the gain of the individual.",
"i18n":{"ko": "기업의 이익은 개인의 이익과 직결된다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Government is a bigger cause of economic inequality than Capitalism is.",
"i18n":{"ko": "우리는 가장 작은 정부와 함께 완전히 기능하는 시장을 가져야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": -5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Economic regulation is necessary for a fair and equal society.",
"i18n":{"ko": "자유방임 경제는 독점을 형성시키고 계층의 양극화를 악화시킨다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I prefer a planned economy over a market economy.",
"i18n":{"ko": "나는 시장경제보다 계획경제를 선호한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "It is necessary for the government to intervene in the economy to protect its consumers.",
"i18n":{"ko": "정부는 소비자를 보호하기 위해 경제에 개입할 필요가 있다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "We need to have more welfare compared to what we have currently.",
"i18n":{"ko": "우리는 우리가 현재 가진 복지보다 더 많은 복지를 가질 필요가 있다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The minimum wage should be increased.",
"i18n":{"ko": "최저임금을 올려야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 5, "c": 0, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
//Dictatorship vs Constitution
{ "question": "The state should be abolished.",
"i18n":{"ko": "국가는 폐지되어야 합니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I would rather have a constitutional monarchy than an absolute monarchy.",
"i18n":{"ko": "나는 차라리 절대왕정보다는 입헌군주제를 택할 것이다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support a constitution that limits the state's power.",
"i18n":{"ko": "강한 정부는 폭정의 위험을 증가시켜 국가를 매우 불안정하게 만든다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "정부가 우리 권리의 원천이 아니기 때문에 권리는 양도할 수 없고 자연스럽습니다.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The state can be best defined as a monopoly on violence.",
"i18n":{"ko": "국가는 폭력에 대한 독점으로 가장 잘 정의될 수 있습니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": -5, "d": 0, "e": 0, "f": 0, "g": 0 } },

{ "question": "A strong government is required for a safe society.",
"i18n":{"ko": "안전한 사회를 위해 강력한 정부가 필요하다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I prioritize security over liberty.",
"i18n":{"ko": "나는 자유보다 안보를 우선시한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I prefer a unitary state over a federal state.",
"i18n":{"ko": "나는 연방 주보다 단일 주를 선호합니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Theoretically, a morally good dictator would bring more good than bad.",
"i18n":{"ko": "사심 없는 독재자의 통치는 내게 이상적이다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Strong governments are more efficient than democratic governments.",
"i18n":{"ko": "나는 민주주의보다 독재를 택하겠다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 5, "d": 0, "e": 0, "f": 0, "g": 0 } },
	
//Particular vs Universal
{ "question": "My nation's ideals are better than most other nations' ideals.",
"i18n":{"ko": "우리나라의 이상은 대부분 나라들의 이상보다 낫다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "The enemy of my enemy is my friend.",
"i18n":{"ko": "적의 적은 나의 친구이다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Foreign intervention is sometimes necessary.",
"i18n":{"ko": "해외에 자유를 제공하기 위해 독재 정권을 침략하는 것은 정당하다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Foreign officials have no right to dictate policy in another country.",
"i18n":{"ko": "외국 관리들은 다른 나라에서 정책을 지시할 권리가 없습니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "My country's borders should be expanded.",
"i18n":{"ko": "조국의 국경을 넓혀야 합니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": -5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "We should avoid conflict when possible.",
"i18n":{"ko": "우리는 가능하면 갈등을 피해야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "Political unions like the EU generally do more harm than good.",
"i18n":{"ko": "국제 동맹은 일반적으로 해롭다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support isolationism.",
"i18n":{"ko": "저는 고립주의를 지지합니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "I support a non-interventionist foreign policy.",
"i18n":{"ko": "우리의 이상을 전파하기보다는 평화와 개별주의에 주로 힘써야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
{ "question": "My country spends too much money on the military.",
"i18n":{"ko": "우리나라는 군대에 너무 많은 돈을 쓴다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 5, "e": 0, "f": 0, "g": 0 } },
	
//Theocracy vs Secular
{ "question": "Public schools should not advocate for any religious belief.",
"i18n":{"ko": "",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "Religion should play a much smaller role in government.",
"i18n":{"ko": "종교는 현재에 비해 훨씬 더 작은 역할을 해야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "Churches should be taxed the same way as how most other organizations are taxed.",
"i18n":{"ko": "대부분의 다른 조직들처럼 교회에도 세금이 부과되어야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "The church and state needs to be seperated.",
"i18n":{"ko": "교회와 국가는 분리되어야 합니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "All theocracies are tyrannies.",
"i18n":{"ko": "모든 신정은 폭정이다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": -5, "f": 0, "g": 0 } },
	
{ "question": "There should be one or more official religion(s) in my country.",
"i18n":{"ko": "우리 나라에는 최소한 하나의 공식 종교가 있어야 합니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
{ "question": "My religion should be spread as much as possible.",
"i18n":{"ko": "나의 종교는 가능한 한 많이 전파되어야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
{ "question": "My nation is inherently a religious nation.",
"i18n":{"ko": "우리 민족은 종교 국가로 건국되었습니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
{ "question": "Secularism is unhealthy for society.",
"i18n":{"ko": "세속주의는 사회에 해롭다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
{ "question": "If I can vote, I would consider the candidates' religious beliefs when voting.",
"i18n":{"ko": "내가 투표할 수 있다면 투표할 때 후보자의 종교적 신념을 고려할 것입니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 5, "f": 0, "g": 0 } },
	
//Acceleration vs Deceleration
{ "question": "Rapid technological advancement causes more harm than good.",
"i18n":{"ko": "급속한 기술 발전은 득보다 실이 많다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },

{ "question": "Life before the industrial revolution was much better.",
"i18n":{"ko": "산업 혁명 이전의 삶은 지금보다 훨씬 더 좋았다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },
	
{ "question": "Modern urban life is unfulfilling because of technological development.",
"i18n":{"ko": "삶이 너무 복잡해지고 있기 때문에 우리는 한 발짝 물러나야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },
	
{ "question": "If given the choice, I would reject an extension of my lifespan by centuries.",
"i18n":{"ko": "선택권이 주어진다면 나는 내 수명을 수백 년 연장하는 것을 거부할 것입니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },
	
{ "question": "Transhumanism is an absurd idea.",
"i18n":{"ko": "트랜스휴머니즘(인간은 자신의 한계를 극복하기 위해 과학과 기술을 통해 인체를 개조해야 한다는 생각)은 터무니없다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": -5, "g": 0 } },
	
{ "question": "It is foolish to expect renewable energy sources to be able to fully replace fossil fuels.",
"i18n":{"ko": "재생 가능 에너지원이 화석 연료를 완전히 대체할 수 있다고 기대하는 것은 어리석은 일입니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },

{ "question": "We should accelerate our technological progress.",
"i18n":{"ko": "우리는 우리의 기술적 진보를 가속화해야 한다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },
	
{ "question": "Promoting nuclear energy is more effective than implementing environmental regulations.",
"i18n":{"ko": "원자력 발전은 환경 규제를 시행하는 것보다 더 효과적입니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },
	
{ "question": "Space colonization as an issue should be considered more seriously.",
"i18n":{"ko": "문제로서의 우주식민화는 보다 심각하게 고려되어야 한다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },
	
{ "question": "Currently, people are too paranoid about AI.",
"i18n":{"ko": "현재 사람들은 AI에 대해 너무 편집증적입니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 5, "g": 0 } },
	
//Assimilation vs Multicultural
{ "question": "Governments should be as concerned about illegal immigrants as they are concerned about ordinary citizens.",
"i18n":{"ko": "불법 이민자들과 일반 시민들은 같은 대우를 받을 자격이 있다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },
	
{ "question": "Most, if not all societies should be a blend of different cultures.",
"i18n":{"ko": "모든 사회는 아니더라도 대부분의 경우 서로 다른 문화가 혼합되어야 합니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },
	
{ "question": "Borders should be as open as possible.",
"i18n":{"ko": "국경은 가능한 한 열려 있어야 합니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },
	
{ "question": "There shouldn't be an official language in my country.",
"i18n":{"ko": "우리나라에는 공식 언어가 없어야 합니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },
	
{ "question": "Nativism is discriminatory in nature.",
"i18n":{"ko": "원주민주의는 본질적으로 차별적입니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": -5 } },

{ "question": "In general, immigrants are bad for the country.",
"i18n":{"ko": "너무 많은 이민자는 경제적 쇠퇴와 이념적 급진화를 불러온다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
{ "question": "Immigrants should be expected to learn the majority language of the country.",
"i18n":{"ko": "이민자들은 그 나라의 대부분의 언어를 배워야 합니다.",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
{ "question": "Immigrants can never really adapt to our way of life.",
"i18n":{"ko": "이민자들은 결코 우리의 생활 방식에 적응할 수 없습니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
{ "question": "There should be a shared and unified cultural identity in my country.",
"i18n":{"ko": "우리나라에는 공유되고 통일된 문화적 정체성이 있어야 합니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
{ "question": "If we accept migrants at all, it is important that they assimilate into our culture.",
"i18n":{"ko": "우리가 이주민을 받아들인다면 그들이 우리 문화에 동화되는 것이 중요합니다. ",
	"ru": "",
	"cn": "",
	"es": ""},
"effect": { "a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0, "g": 5 } },
	
];
